import {
  ArrowDown,
  ArrowUpDown,
  Baby,
  Bath,
  BedDouble,
  Bell,
  Car,
  CarFront,
  Check,
  ChevronDown,
  Cigarette,
  CigaretteOff,
  CircleAlert,
  ClipboardCheck,
  CookingPot,
  Copy,
  Dumbbell,
  Fence,
  Flame,
  Instagram,
  KeyRound,
  LockKeyhole,
  LogIn,
  LogOut,
  type LucideIcon,
  type LucideProps,
  MapPin,
  PartyPopper,
  PawPrint,
  PersonStanding,
  Phone,
  Snowflake,
  Sofa,
  Sparkles,
  Sun,
  Thermometer,
  Tv,
  Users,
  Utensils,
  WashingMachine,
  Waves,
  Wifi,
} from "lucide-react";

/**
 * Registry for the kebab-case icon names emitted by lib/domain/display.ts plus
 * the ones used by the guide layout. Static map (no dynamic import) so every
 * icon is tree-shaken at build time; unknown names fall back to a check mark
 * instead of rendering nothing.
 */
const ICONS: Record<string, LucideIcon> = {
  "arrow-down": ArrowDown,
  "arrow-up-down": ArrowUpDown,
  baby: Baby,
  bath: Bath,
  "bed-double": BedDouble,
  bell: Bell,
  car: Car,
  "car-front": CarFront,
  check: Check,
  "chevron-down": ChevronDown,
  cigarette: Cigarette,
  "cigarette-off": CigaretteOff,
  "circle-alert": CircleAlert,
  "clipboard-check": ClipboardCheck,
  "cooking-pot": CookingPot,
  copy: Copy,
  dumbbell: Dumbbell,
  fence: Fence,
  flame: Flame,
  instagram: Instagram,
  "key-round": KeyRound,
  "lock-keyhole": LockKeyhole,
  "log-in": LogIn,
  "log-out": LogOut,
  "map-pin": MapPin,
  "party-popper": PartyPopper,
  "paw-print": PawPrint,
  "person-standing": PersonStanding,
  phone: Phone,
  snowflake: Snowflake,
  sofa: Sofa,
  sparkles: Sparkles,
  sun: Sun,
  thermometer: Thermometer,
  tv: Tv,
  users: Users,
  utensils: Utensils,
  "washing-machine": WashingMachine,
  waves: Waves,
  wifi: Wifi,
};

export type IconProps = Omit<LucideProps, "ref"> & { name: string };

export function Icon({ name, ...props }: IconProps) {
  const Glyph = ICONS[name] ?? Check;
  return <Glyph aria-hidden="true" {...props} />;
}
